# Configuración de Prometheus para BetiBot
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "betibot_rules.yml"

scrape_configs:
  # Métricas de la aplicación principal
  - job_name: 'betibot-app'
    static_configs:
      - targets: ['betibot:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métricas de Celery
  - job_name: 'betibot-celery'
    static_configs:
      - targets: ['celery:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métricas de Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métricas de Flower
  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métricas de Prometheus (self-monitoring)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métricas de Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métricas de Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

# Configuración de alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuración de almacenamiento
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB

